name: build test

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install build-essential libreadline-dev libssl-dev
    - name: build
      run: ./build.sh

  mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: brew install readline openssl
    - name: build
      run: ./build.sh

  windows:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          gcc
          libreadline-devel
          libcrypt-devel
          openssl-devel
          zlib-devel
    - name: build
      run: ./build.sh
      shell: bash
